# Site settings
title: Devices and Sensors Working Group
email: public-device-apis@w3.org
description: > # this means to ignore newlines until "theme:"
  Enables web apps to interact with device hardware and sensors.
theme: jekyll-theme-modernist
baseurl: "/das-wg" # the subpath of the site